services:
  vpn:
    image: ghcr.io/thrnz/docker-wireguard-pia:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LOC=${PIA_LOCATION}
      - USER=${PIA_USER}
      - PASS=${PIA_PASS}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - PORT_FORWARDING=1
      - PORT_PERSIST=1
      - PORT_SCRIPT=/pia-shared/portupdate-qbittorrent.sh
      - FIREWALL=0
      - RECONNECT=1
    volumes:
      - ./pia:/pia
      - ./pia-shared:/pia-shared
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    restart: unless-stopped
    ports:
      - "8080:8080"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENT_PORT=51697
    volumes:
      - ./qbittorrent:/config
      - ${MEDIA_ROOT}:/data
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./jellyfin:/config
      - ${MEDIA_ROOT}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "1900:1900/udp"
    restart: unless-stopped
