services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - PODMAN_USERNS=keep-id
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - DNS_ADDRESS=${DNS}
      - WIREGUARD_ENDPOINT_IP=${WG_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WG_ENDPOINT_PORT}
      - WIREGUARD_ADDRESSES=${WG_ADDRESS}
      - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${WG_PUBLIC_KEY}
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=private internet access
      - VPN_PORT_FORWARDING_USERNAME=${PIA_USER}
      - VPN_PORT_FORWARDING_PASSWORD=${PIA_PASS}
      - SERVER_NAMES="kawaserver"
      - TZ=${TIMEZONE}
    volumes:
      - ./gluetun:/gluetun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - vpn_net
    ports:
      - "8080:8080"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    cap_add:
      - SYS_ADMIN
    environment:
      - PODMAN_USERNS=keep-id
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ${MEDIA_ROOT}:/data:z
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    cap_add:
      - SYS_ADMIN
    environment:
      - PODMAN_USERNS=keep-id
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./jellyfin:/config
      - ${MEDIA_ROOT}:/data:z
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "1900:1900/udp"
    restart: unless-stopped
    networks:
      - jellyfin_net
      - vpn_net

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24
  jellyfin_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
