services:
  # vpn:
  #   image: qmcgaw/gluetun
  #   container_name: vpn
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_ADMIN
  #   environment:
  #     - PODMAN_USERNS=keep-id
  #     - VPN_SERVICE_PROVIDER=custom
  #     - VPN_TYPE=wireguard
  #     - DNS_ADDRESS=${DNS}
  #     - WIREGUARD_ENDPOINT_IP=${WG_ENDPOINT_IP}
  #     - WIREGUARD_ENDPOINT_PORT=${WG_ENDPOINT_PORT}
  #     - WIREGUARD_ADDRESSES=${WG_ADDRESS}
  #     - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}
  #     - WIREGUARD_PUBLIC_KEY=${WG_PUBLIC_KEY}
  #     # - VPN_PORT_FORWARDING=on
  #     # - VPN_PORT_FORWARDING_PROVIDER=private internet access
  #     # - VPN_PORT_FORWARDING_USERNAME=${PIA_USER}
  #     # - VPN_PORT_FORWARDING_PASSWORD=${PIA_PASS}
  #     # - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":{{PORT}},\"current_network_interface\":\"{{VPN_INTERFACE}}\",\"random_port\":false,\"upnp\":false}" http://127.0.0.1:8080/api/v2/app/setPreferences'
  #     # - VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" http://127.0.0.1:8080/api/v2/app/setPreferences'
  #     - SERVER_NAMES="kawaserver"
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - ./gluetun:/gluetun
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #     - net.ipv6.conf.default.disable_ipv6=1
  #     - net.ipv6.conf.all.disable_ipv6=1
  #   restart: unless-stopped
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   networks:
  #     - vpn_net
  #   ports:
  #     - "8080:8080"

  vpn:
    networks:
      vpn_net:
        ipv4_address: 10.100.0.2
    extra_hosts:
      - "jellyfin:10.100.0.3"
    image: ghcr.io/thrnz/docker-wireguard-pia:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LOC=sg
      - USER=${PIA_USER}
      - PASS=${PIA_PASS}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - PORT_FORWARDING=1
      - PORT_SCRIPT=/pia-shared/portupdate-qbittorrent.sh
      - FIREWALL=0
      - RECONNECT=1
      - TZ=${TIMEZONE}
      - QBT_USER=${QBT_USER}
      - QBT_PASS=${QBT_PASS}
    volumes:
      - ./pia:/pia
      - ./pia-shared:/pia-shared
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "51697:51697/tcp"
      - "51697:51697/udp"
      - "9000:9000" # Maps the exporter's port to your host
      - "7878:7878" # Radarr
      - "8989:8989" # Sonarr
      - "9696:9696" # Prowlarr
      - "6767:6767" # Bazarr
      - "8096:8096" # Jellyfin
      - "7359:7359/udp" # Jellyfin DLNA
      - "1900:1900/udp" # Jellyfin SSDP

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENT_PORT=51697
    volumes:
      - ./qbittorrent:/config
      - ${MEDIA_ROOT}:/data
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped

  qbittorrent-exporter:
    image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter:latest
    container_name: qbittorrent-exporter
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    environment:
      # qBittorrent Connection Settings
      - QBITTORRENT_HOST=127.0.0.1
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USER=${QBT_USER}
      - QBITTORRENT_PASS=${QBT_PASS}
      - QBITTORRENT_SSL=False # Set to True if using HTTPS
      # Optional Exporter Settings
      - EXPORTER_PORT=9000
      - EXPORTER_LOG_LEVEL=ERROR

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    cap_add:
      - SYS_ADMIN
    environment:
      - PODMAN_USERNS=keep-id
      - TZ=${TIMEZONE}
    volumes:
      - ./jellyfin:/config
      - ${MEDIA_ROOT}:/data:z
      - /etc/localtime:/etc/localtime:ro
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped
      

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./prowlarr:/config
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr:/config
      - ${MEDIA_ROOT}:/data # Mount entire media root for movies and downloads
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr:/config
      - ${MEDIA_ROOT}:/data # Mount entire media root for tvshows and downloads
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:development-version-v1.5.7-beta.47
    container_name: bazarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./bazarr:/config
      - ${MEDIA_ROOT}:/data # Mount entire media root for movie/tv subtitles
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_started
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:vpn"
    environment:
      - LOG_LEVEL=info
      - LOG_FILE=none
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Singapore
    ports:
      - "${PORT:-8191}:8191"
    volumes:
      - ./flaresolver:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=info
      - TZ=${TIMEZONE}
      - PORT=5055
    volumes:
      - ./seerr:/app/config
    ports:
      - "5055:5055"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 10.100.0.4
      jellyfin_net:
        ipv4_address: 10.200.0.3


networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24
  jellyfin_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
